### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by Rishikantpd** [4teamwork/cypress-drag-drop#56]
I have made a change in index.js

if (isAttached(this.targetElement)) {
          this.target
            .trigger('mouseup', {
              **force: true,**    //i have added this line
              which: 1,
              button: 0,

but it is not reflecting in run time

**Comment by lvonlanthen** [comment]
This does not work because `this.options` overwrites it a couple of lines later (https://github.com/4teamwork/cypress-drag-drop/blob/master/index.js#L65) and `this.options` contains `force: false` as default value.

I don't think you should change the `index.js` file directly, you should rather pass `force` as an option when calling `.drag()`. As an example: `cy.get('.sourceitem').drag('.targetitem', { force: true })` or refer to https://github.com/4teamwork/cypress-drag-drop/blob/master/tests/specs/force.spec.js for another example.
